### ISSUE TITLE
How to use (external-acces-hook "query") function for an external database?

### ISSUE THREAD

**Issue by KIlian42** [shop-planner/shop3#35]
Dear Mr Goldman,

I'm currently working with shop3 in my thesis and I´m struggling (sorry I´m using lisp for the first time) with the hook function to use an external database (and the manual does not make it clear enough for me). Where do I need to put the file path of the database. And also If I try to use (external-acces-hook "?") I get
"The function SHOP3.THEOREM-PROVER:EXTERNAL-ACCESS-HOOK is undefined."
Furthermore do I also need to put any arguments in the (find-plans ...) function, or what does the explanation keyword has to do with it?

Could You please give me an example (for fools) how to use it?

Many thanks
Kilian Kramer

**Comment by rpgoldman** [comment]
@ukuter -- do you have any examples that use this that you could share?

@KIlian42 -- I don't have an example myself, but if you could give us a concrete example, we could probably point you in the right direction.  Here's what I suggest: make an excruciatingly simple sqlite data base with a piece of information you want to get out of it.  Post that example here, with code that sets up the sqlite database (bash, python, perl, something like that).  If you can do that, I will work with you to grow that into a sort of tutorial, while getting you something you can use for your thesis.

`external-access-hook` is a function that you must define.  There's an example, `DUMMY-external-access-hook` in theorem-prover.lisp that you can look at, but it's probably not as helpful an example as you would like, since it only shows what you should return, not how to engage with an external system. To be honest, it's also possible that it is bit-rotted, since it makes bindings by hand. So let's get that done as part of this tutorial.

**Comment by KIlian42** [comment]
Thanks for Your very quick response. Sorry, I wasn't clear enough and I don't have the time for setting up a Sqlite example right now. So actually I hope I just could integrate atoms from an external file just like database.txt or database.lisp into my planner like 

[durations.txt](https://github.com/shop-planner/shop3/files/5210807/durations.txt)

So I thought whenever I use a method or operator with the keyword :external in the preconditions it will look up in this file first...because I have huge amounts of atoms (about graph, durations ...) so I just wanted to separated the (problem definition) informations from my planner into a database.txt file and thought could use it somehow with the keyword :external.

**Comment by KIlian42** [comment]
<img width="635" alt="Bildschirmfoto 2020-09-11 um 20 08 54" src="https://user-images.githubusercontent.com/57774167/92958496-a0d13f80-f46a-11ea-815d-013cdd40f89a.png">


-

**Comment by KIlian42** [comment]
I tried to use it somehow in that way. ^^ (but of course this does not work)

<img width="636" alt="Bildschirmfoto 2020-09-11 um 20 20 23" src="https://user-images.githubusercontent.com/57774167/92959669-86986100-f46c-11ea-97a2-aae1162d694b.png">

Many regards
Kilian

**Comment by KIlian42** [comment]
I thought I could use it somehow in that way. (but of course this does not work)

<img width="637" alt="Bildschirmfoto 2020-09-11 um 21 17 33 2" src="https://user-images.githubusercontent.com/57774167/92964535-90be5d80-f474-11ea-9a65-052399a33d98.png">

Many regards
Kilian

**Comment by rpgoldman** [comment]
What I would suggest for that is much simpler.  I'm going to assume that you are making SHOP planning problems something like this:

``` lisp
(defparameter *prob1* (make-problem 'my-problem my-state-list my-task-list))
```

What you could do is something like the following:

```
(defparameter *durations*
    (with-open-file (str "/User/database.txt")
        (loop :for x = (read str nil nil) :while x :collect x)))

(defparameter *prob1* (make-problem
                                        'my-problem
                                        ;; now you add the durations to the initial state
                                        (append *durations* my-state-list)
                                        my-task-list))
```

Now you can just use the `duration` facts like any other fact.

P.S. Some combination of Peter Seibel's *Practical Common Lisp* and Peter Norvig's *Paradigms of AI Programming* may help you with the lisp

**Comment by rpgoldman** [comment]
@KIlian42 Reopen this if that doesn't work.

**Comment by KIlian42** [comment]
Many thanks! It works.

**Comment by KIlian42** [comment]
<img width="1274" alt="Bildschirmfoto 2020-09-12 um 12 19 16" src="https://user-images.githubusercontent.com/57774167/92993493-4d0a3900-f4f2-11ea-8d0d-7c8ad8549d7d.png">
